apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payload-secrets
  namespace: teck-website-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teck-website-vault
    kind: SecretStore
  target:
    name: payload-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: teck-website/payload
        property: secret
    - secretKey: preview-secret
      remoteRef:
        key: teck-website/payload
        property: preview-secret
