apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payload-secrets
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Ensure secrets are created after setup
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teck-website-vault
    kind: ClusterSecretStore
  target:
    name: payload-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: {{ .Values.global.vaultPath | default "teck-website" }}/payload
        property: secret
    - secretKey: preview-secret
      remoteRef:
        key: {{ .Values.global.vaultPath | default "teck-website" }}/payload
        property: preview-secret
    {{- if eq (.Values.global.environment | default "production") "preview" }}
    - secretKey: session-secret
      remoteRef:
        key: {{ .Values.global.vaultPath }}/payload
        property: session-secret
    - secretKey: environment
      remoteRef:
        key: {{ .Values.global.vaultPath }}/payload
        property: environment
    {{- end }}
