apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: {{ .Values.global.namespace | default "teck-website-prod" }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teck-website-vault
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
        property: password
    - secretKey: username
      remoteRef:
        key: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
        property: username
