apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: teck-website-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teck-website-vault
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: teck-website/postgres
        property: password
    - secretKey: username
      remoteRef:
        key: teck-website/postgres
        property: username
