apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: teck-website-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teck-website-vault
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: teck-website/redis
        property: password
