apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: teck-website-vault
  namespace: teck-website-prod
spec:
  provider:
    vault:
      server: "http://vault.vault-system:8200"
      path: "teck-website"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "vault-secret"
            key: "vault-role-id"
          secretRef:
            name: "vault-secret"
            key: "vault-secret-id"


