apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: teck-website-vault
spec:
  provider:
    vault:
      server: "http://vault-active.vault-system:8200"
      path: "teck-website"
      version: "v2"
      auth:
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "a40549f2-2974-d61f-7f2d-56e3276c1a64"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "app-role-secret-id"
            key: "secret-id"
            namespace: "external-secrets"


