apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: teck-website-vault
  namespace: teck-website-prod
spec:
  provider:
    vault:
      server: "http://vault-active.vault-system:8200"
      path: "teck-website"
      version: "v2"
      auth:
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "6119304e-1276-67f6-fe7c-df19cb12474a"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "app-role-secret-id"
            key: "secret-id"
            namespace: "external-secrets"


