apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teck-website-prod
    server: { { .Values.spec.destination.server } }
  project: default
  source:
    path: deployment/infrastructure/postgres
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
