apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.label.name | default "teck-website" }}-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.global.namespace | default .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
    - repoURL: "registry-1.docker.io/bitnamicharts"
      targetRevision: 20.13.4
      chart: redis
      helm:
        releaseName: redis
        valueFiles:
          - $values/deployment/infrastructure/redis/values.yaml
        parameters:
          {{- if .Values.global.environment }}
          - name: global.environment
            value: {{ .Values.global.environment }}
          {{- end }}
    - repoURL: https://github.com/CaptainPowerTurtle/teck-website-monorepo.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
