global:
  defaultStorageClass: longhorn
  storageClass: longhorn
  namespace: "{{ .Values.global.namespace | default \"teck-website-prod\" }}"
  environment: "{{ .Values.global.environment | default \"production\" }}"
  vaultPath: "{{ .Values.global.vaultPath | default \"teck-website\" }}"
architecture: standalone
persistence:
  enabled: {{ if eq (.Values.global.environment | default "production") "preview" }}false{{ else }}true{{ end }}
  {{- if ne (.Values.global.environment | default "production") "preview" }}
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 500Mi
  {{- end }}
extraDeploy:
  - apiVersion: external-secrets.io/v1alpha1
    kind: PushSecret
    metadata:
      name: redis-pushsecret
      namespace: "{{ .Values.global.namespace }}"
    spec:
      secretStoreRefs:
      - name: teck-website-vault
        kind: ClusterSecretStore
      selector:
        secret:
          name: redis
      refreshInterval: 30s
      data:
        - match:
            secretKey: redis-password
            remoteRef:
              remoteKey: "{{ .Values.global.vaultPath }}/redis"
              property: password