apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: {{ if eq (.Values.global.environment | default "production") "preview" }}2{{ else }}2{{ end }}
  startDelay: 10
  stopDelay: 10
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: teck-website
      owner: app

  postgresql:
    parameters:
      max_worker_processes: "60"
    pg_hba:
      # To access through TCP/IP you will need to get username
      # and password from the secret cluster-example-custom-app
      - host all all all scram-sha-256

  {{- if eq (.Values.global.environment | default "production") "preview" }}
  # Use Longhorn storage for preview environments - will be cleaned up when namespace is deleted
  storage:
    storageClass: longhorn-postgres-storage
    size: 5Gi
  walStorage:
    storageClass: longhorn-postgres-storage
    size: 5Gi
  {{- else }}
  # Use persistent storage for production
  storage:
    storageClass: longhorn-postgres-storage
    size: 10Gi
  walStorage:
    storageClass: longhorn-postgres-storage
    size: 10Gi
  {{- end }}

  # prometheus
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-postgres-rw
  namespace: {{ .Values.global.namespace }}
spec:
  cluster:
    name: postgres

  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"