apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres-pushsecret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy after postgres cluster and secrets are created
spec:
  secretStoreRefs:
    - name: teck-website-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-app  # CloudNativePG creates this secret automatically
  refreshInterval: 30s
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
          property: password