apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret
  namespace: teck-website-prod
spec:
  secretStoreRefs:
    - name: teck-website-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-app
  refreshInterval: 30s
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: postgres
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: postgres
          property: password
