apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres-pushsecret
  namespace: {{ .Values.global.namespace }}
spec:
  secretStoreRefs:
    - name: teck-website-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-app
  refreshInterval: 30s
  data:
    - match:
        secretKey: username
      remoteRef:
        remoteKey: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
        property: username
    - match:
        secretKey: password
      remoteRef:
        remoteKey: {{ .Values.global.vaultPath | default "teck-website" }}/postgres
        property: password