version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=latest
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  minio_data:
  redis-data:
