{{- if eq .Values.global.environment "preview" }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  kubernetesConfig:
    image: redis:8.0.3
    imagePullPolicy: IfNotPresent
  size: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  redisPasswordSecret:
    name: redis-password
    key: password
{{- else }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  kubernetesConfig:
    image: redis:8.0.3
    imagePullPolicy: IfNotPresent
  size: 3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
  redisPasswordSecret:
    name: redis-secret
    key: password
{{- end }}