{{- if eq .Values.global.environment "preview" }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  kubernetesConfig:
    image: redis:8.0.3
    imagePullPolicy: IfNotPresent
    updateStrategy: {}
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    redisSecret:
      key: password
      name: redis-password
  size: 1
{{- else }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  kubernetesConfig:
    image: redis:8.0.3
    imagePullPolicy: IfNotPresent
    updateStrategy: {}
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 256Mi
    redisSecret:
      key: password
      name: redis-secret
  size: 3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
{{- end }}