{{- if eq .Values.global.environment "preview" }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  image: redis:8.2-alpine
  replicas: 1
  # No storage section = no persistence
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  passwordSecret:
    name: redis-password
    key: password
{{- else }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 3
  clusterReplicas: 1
  image: redis:8.2-alpine
  storage:
    className: longhorn
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 1Gi
  passwordSecret:
    name: redis-secret
    key: password
{{- end }}