global:
  namespace: teck-website-prod
  environment: production
  label:
    name: teck-website
  vaultPath: production

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: teck-website-prod
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CaptainPowerTurtle/teck-website-monorepo
    targetRevision: HEAD
  project: teck-website

web:
  ingress:
    host: teck.dk
  containers:
    image:
      tag: 1.10.1
