global:
  namespace: teck-website-prod
  environment: production
  label:
    name: teck-website
  vaultPath: teck-website

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: teck-website-prod
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CaptainPowerTurtle/teck-website-monorepo
    targetRevision: b70b90d
  project: teck-website
