global:
  namespace: teck-website-prod
  environment: production
  label:
    name: teck-website
  vaultPath: teck-website

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: teck-website-prod
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CaptainPowerTurtle/teck-website-monorepo
    targetRevision: 688e921d9c32a79d5a037f5ca66b6229d9d9429f
  project: teck-website
