global:
  namespace: "{{ .Values.global.namespace | default \"teck-website-prod\" }}"
  environment: "{{ .Values.global.environment | default \"production\" }}"
  label:
    name: "{{ .Values.global.label.name | default \"teck-website\" }}"
  vaultPath: "{{ .Values.global.vaultPath | default \"teck-website\" }}"

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .Values.global.namespace | default \"teck-website-prod\" }}"
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CaptainPowerTurtle/teck-website-monorepo
    targetRevision: HEAD
  project: teck-website
