global:
  namespace: teck-website-prod
  environment: production
  label:
    name: teck-website-web

environment: production
web:
  label:
    name: teck-website-web
  namespace: teck-website-prod
  replicas: 2

  containers:
    name: teckwebsite-web
    ports:
      containerPort: 3000

    image:
      registry: ghcr.io
      name: captainpowerturtle/teck-website-monorepo/web
      tag: 1.2.4
      imagePullPolicy: Always
    resources:
      limits:
        cpu: "500m"
        memory: 1500Mi
  service:
    port: 3000
    targetPort: 3000
  ingress:
    schema: https
    host: teck.dk
