global:
  namespace: teck-website-prod
  environment: production
  label:
    name: teck-website-web

web:
  label:
    name: "{{ .Values.global.label.name | default \"teck-website-web\" }}"
  namespace: "{{ .Values.global.namespace | default \"teck-website-prod\" }}"
  replicas: 2

  containers:
    name: teckwebsite-web
    ports:
      containerPort: 3000

    image:
      registry: ghcr.io
      name: captainpowerturtle/teck-website-monorepo/web
      tag: "{{ .Values.web.containers.image.tag | default \"1.2.4\" }}"
      imagePullPolicy: Always
    resources:
      limits:
        cpu: "500m"
        memory: 1500Mi
  service:
    port: 3000
    targetPort: 3000
  ingress:
    schema: https
    host: teck.dk
