name: Manual Container Cleanup

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Fetch multi-platform digests for all SHA-only tags
        id: multi-arch-digests
        run: |
          IMAGE="ghcr.io/captainpowerturtle/teck-website-monorepo/web"
          DIGESTS=""
          SHA_TAGS=$(gh api users/CaptainPowerTurtle/packages/container/teck-website-monorepo%2Fweb/versions | jq -r '.[] | select(.metadata.container.tags? | length == 1 and (.metadata.container.tags[0] | test("^[a-f0-9]{40}$"))) | .metadata.container.tags[0]')
          for SHA in $SHA_TAGS; do
            ARCH_DIGESTS=$(docker manifest inspect $IMAGE:$SHA | jq -r '.[0].manifests[].digest' | paste -s -d ' ' -)
            DIGESTS="$DIGESTS$ARCH_DIGESTS,"
          done
          DIGESTS=$(echo $DIGESTS | sed 's/,$//')
          echo "multi-arch-digests=$DIGESTS" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Retention Policy
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          image-names: teck-website-monorepo/web
          tag-selection: both
          image-tags: '[a-f0-9]{40}'   # regex for SHA tags
          skip-shas: ${{ steps.multi_arch_digests.outputs.multi_arch_digests }}
          cut-off: 0d
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
