name: Setup Preview Environment

on:
  pull_request:
    types: [labeled]
    branches:
      - main
      - feature/**
      - bugfix/**
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'deployment/**'

permissions:
  id-token: write
  contents: read

jobs:
  setup-preview-secrets:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    
    steps:
      - name: Install Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
      
      - name: Setup Vault with JWT
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: github-actions
          exportToken: true

      - name: Create Default Preview Secrets
        run: |
          PR_NUMBER=${{ github.event.number }}
          NAMESPACE="preview-${PR_NUMBER}"
          VAULT_PATH="teck-website/${NAMESPACE}"
          
          echo "Setting up default secrets for preview environment: ${VAULT_PATH}"
          
          # Generate random secrets for preview environment
          RANDOM_PAYLOAD_SECRET=$(openssl rand -hex 32)
          RANDOM_PREVIEW_SECRET=$(openssl rand -hex 16)
          RANDOM_SESSION_SECRET=$(openssl rand -hex 24)
          
          # Create payload secrets with generated values
          vault kv put ${VAULT_PATH}/payload \
            secret="$RANDOM_PAYLOAD_SECRET" \
            preview-secret="$RANDOM_PREVIEW_SECRET" \
            session-secret="$RANDOM_SESSION_SECRET" \
            environment="preview" \
            pr-number="${PR_NUMBER}"
          
          # Optional: Create other default secrets that might be needed
          vault kv put ${VAULT_PATH}/postgres \
            username="preview_user" \
            password="$(openssl rand -hex 16)" \
            database="preview_${PR_NUMBER}" \
            host="postgres.preview-${PR_NUMBER}.svc.cluster.local"
          
          vault kv put ${VAULT_PATH}/redis \
            password="$(openssl rand -hex 12)" \
            host="redis.preview-${PR_NUMBER}.svc.cluster.local" \
            port="6379"
          
          echo "✅ Created default secrets for preview environment: ${VAULT_PATH}"
          echo "   - Payload secrets: ✅"
          echo "   - Database secrets: ✅" 
          echo "   - Redis secrets: ✅"
          echo "Preview environment is ready to deploy!"
