apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.web.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.teck.dk`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: 3000
    - match: Host(`teck.dk`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: 3000
