apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.web.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik-external
    argocd.argoproj.io/sync-wave: "3"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.{{ .Values.web.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: 3000
      middlewares:
        - name: default-headers
    - match: Host(`{{ .Values.web.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: 3000
      middlewares:
        - name: default-headers
