apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "web.fullname" . }}-ingress"
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.web.ingress.host | default "localhost" }}`)
      middlewares:
        - name: "{{ .Values.global.resourcePrefix | default "" }}default-headers"
      services:
        - name: "{{ include "web.fullname" . }}-service"
          port: 3000